language: python
os: linux
dist: bionic

branches:
  only:
  - master

before_deploy:
- git config --local user.name "cmorganl"
- git config --local user.email "c.morganlang@gmail.com"

deploy:
  provider: pypi
  username: __token__
  password:
    secure: ojR1vQ4O/dpt/YkgBbi8qpxqR0xP9a7daDjjs0QPXt0JVaRpF22OwTeHmzZFFRmR9HtlAT1caP9WFUjrCvns134vbSdNyoBiNLD3xAz54IICVEMzAv5NTBAZwj6YfwieQatjr2JUYPyB0lo6vynBQK4S9gErMvxpGfTcNKmcoJ/fPTm18jRZWypvaBfAE/wE3MVbBEPf9wTfiMfvYNFRIA3axWvttoKwMfQ+RmeZEDNZPD+dbHkVy48Y4hwcHooa8ILcZdg6u6kKqNf2+MdvYDZ+jsposlT85DNtO58OHJheVryiymgGwNEdrmFmVghxXtiu/3xNYWYrhGf1sQ48c+JdgLKFd/L3HSkAyGjupuP3nX0E953W2XYAqEosTuW3Res0xKgeIjsraDGOzUaZQaE4Lmy/vWc9X1Kx5R/R2VRs0N6qMbkdbqlsziswIEcojVkuk1cQ2QqbE9VTiC3bHeLFtMecn1JoxOSLCIHKhaWt4X9CasyOd6Bsr6PGQ+28w6VmuoNc97EDHOSjI6oNYVPC/wPFC1u+3JD755m6Nsr3UAbMfCXYBey6VNxu74YI9IDw3ct/YIHVVbCuCS2jnPCUouRTJhpc32vxS//4sNeJOoi2XII0vjdaNQBs2hiR7qCvfgM+08PaOd3o1flz3xEaxOc14QgZ5AQQ8+6yZ9k=
  on:
    branch: master
  skip_existing: true
  distributions: "sdist bdist_wheel"
  cleanup: false

env:
  global:
  - CIBW_SKIP="cp27-* pp27-* *-manylinux_i686"
  - TWINE_USERNAME=__token__
  # Note: TWINE_PASSWORD is set to an API token in Travis settings
  - PIP="python3 -m pip"
  - TWINE_REPOSITORY=pypi
  - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/
  - TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}

jobs:
  include:
  - services: docker
  - os: osx
    language: shell

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      git -C "$(brew --repo)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git;
    fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      sudo apt -y install gcc dpkg-dev curl zip git libz-dev python3-distutils python3-dev;
    fi

install:
  - "$PIP install -r requirements.txt"
  - "$PIP install -U setuptools"
  - "$PIP install cibuildwheel==1.1.0"
  - "$PIP install --upgrade pip"
  - "$PIP install twine"
  - "$PIP install tox"
  - "$PIP --version"

script:
- tox -v
- python3 -m cibuildwheel --output-dir wheelhouse
- python3 setup.py sdist --dist-dir wheelhouse

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
- ls wheelhouse/
- |
  if [[ $TRAVIS_TAG ]]; then
    python3 -m twine upload --skip-existing wheelhouse/*.whl
  fi
