language: python
os: linux
dist: xenial

branches:
  only:
    - master

python:
  - "3.5"
  - "3.6"
  - "pypy3"

install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

# command to run tests
script:
  - tox -v

notifications:
  email:
    on_success: never
    on_failure: always